apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  #수를 조정할때 사용/ kubectl scale명령어로 해도됨
  replicas: 3
  selector:
    matchLabels:
      app: nginx # 같아야함
  template:
    metadata: 
      #replicaset은 이름 잘 안씀
      labels:
        app: nginx # 같아야함
    spec: 
      containers:
      - name: nginx
        image: nginx:1.19
    