apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  selector:
    app: my-nginx
  ports:
  - protocol: TCP
  # 컨테이너 내부의 80포트가 서비스의 9080포트로 연결될거다
    port: 9080
    targetPort: 80